/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.de.bioinformática;
import Estructura_de_datos.Lista;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 * Ventana para seleccionar y cargar archivos de texto con secuencias de ADN.
 * Proporciona una interfaz para buscar archivos y pasar la cadena de ADN al menú principal.
 * @author Diego Arreaza y Vyckhy Sarmiento
 * @see Menu
 */
public class Busqueda_Archivo extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Busqueda_Archivo.class.getName());
    private int retorno;
    private File Archivo;
    private FileReader Texto;
    private BufferedReader lector;
    /**
     * Creates new form Busqueda_Archivo
     */
    public Busqueda_Archivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Buscar = new javax.swing.JButton();
        getDireccion = new javax.swing.JTextField();
        Siguiente = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        jPanel1.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        getDireccion.setEditable(false);
        getDireccion.setBackground(new java.awt.Color(255, 255, 255));
        getDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(getDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 250, -1));

        Siguiente.setText("Siguiente");
        Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(Siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, -1, -1));

        Exit.setBackground(new java.awt.Color(255, 0, 0));
        Exit.setText("X");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 70, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("     Bienvenido, porfavor ingrese la direccion del \n                            archivo Cadena.txt\n\n\t      ---PASOS---\nHaga click en el boton buscar, saldra una nueva\nventana, tendra que dirigirse hacia la carpeta de \n      la aplicacion y hacer selecionar el archivo\n   Cadena.txt. Luego presione el boton siguiente\n                                 para continuar.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 290, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        JFileChooser Buscador = new JFileChooser();
        Buscador.setDialogTitle("Buscar Archivo");
        
        FileNameExtensionFilter filter = new FileNameExtensionFilter("letras","txt"); 
        Buscador.setFileFilter(filter);
        Buscador.setFileSelectionMode(JFileChooser.FILES_ONLY);
        retorno = Buscador.showOpenDialog(this);
        
        if (retorno == JFileChooser.APPROVE_OPTION){
            Archivo = Buscador.getSelectedFile();
            getDireccion.setText(Archivo.getPath());
            this.setVisible(true);  
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteActionPerformed
        // TODO add your handling code here:
        String cadena =  "";
        if (getDireccion.getText().equals("")){
            getDireccion.setText("Error. No se a seleccionado el archivo diccionario");
        }else{
            if (retorno == JFileChooser.APPROVE_OPTION){
            try {
                // TODO add your handling code here:
                String Direccion = Archivo.getPath();
                Texto = new FileReader(Direccion);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Busqueda_Archivo.class.getName()).log(Level.SEVERE, null, ex);
            }    
                    
            lector = new BufferedReader(Texto);
            String x;
            
            try {
                while ((x = lector.readLine())!= null){
                    cadena = cadena+x;
                }
                
            } catch (IOException ex) {
                System.getLogger(Busqueda_Archivo.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            this.setVisible(false);
            Menu v1 = new Menu(cadena);
            }
            
        }

            
    }//GEN-LAST:event_SiguienteActionPerformed

    private void getDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_getDireccionActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Busqueda_Archivo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Siguiente;
    private javax.swing.JTextField getDireccion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
