/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.de.bioinformática;

import Estructura_de_datos.ArbolBinarioDeBusqueda;

/**
 * Ventana para identificar patrones de ADN con frecuencia máxima/mínima.
 * Utiliza el árbol binario de búsqueda para obtener resultados eficientes.
 * @author Diego Arreaza y Vyckhy Sarmiento
 * @see ArbolBinarioDeBusqueda
 * @see patronADN
 */
public class Ver_Max_Min extends javax.swing.JFrame {

    /**
     * Creates new form duende2
     */
    /**
     * String que explicara que va a buscar en el arbol
     */
    private String Frecuencia;
    /**
     * Arbol organizado por la frecuencia y encargaddo de realizar la busqueda
     */
    private ArbolBinarioDeBusqueda arbol;
    /**
     * Clase que contiene a la ventana menu
     */
    private static Menu menu; 
    
    public Ver_Max_Min(Menu menu) {
        this.menu = menu;
        initComponents();
        arbol = menu.get_Arbol();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Resultado = new javax.swing.JTextField();
        Exit = new javax.swing.JButton();
        Minimo = new javax.swing.JButton();
        Maximo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Resultado.setEditable(false);
        Resultado.setBackground(new java.awt.Color(255, 255, 255));
        Resultado.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        Resultado.setForeground(new java.awt.Color(0, 0, 0));
        Resultado.setText("Aqui se mostrara el resultado de la busqueda");
        Resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResultadoActionPerformed(evt);
            }
        });
        jPanel1.add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 580, -1));

        Exit.setBackground(new java.awt.Color(255, 0, 0));
        Exit.setText("X");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 60, -1));

        Minimo.setBackground(new java.awt.Color(255, 255, 255));
        Minimo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Minimo.setForeground(new java.awt.Color(0, 0, 0));
        Minimo.setText("Tripleta con el minimo de frecuecia");
        Minimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinimoActionPerformed(evt);
            }
        });
        jPanel1.add(Minimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 50));

        Maximo.setBackground(new java.awt.Color(255, 255, 255));
        Maximo.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        Maximo.setForeground(new java.awt.Color(0, 0, 0));
        Maximo.setText("Tripleta con el maximo de frecuecia");
        Maximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaximoActionPerformed(evt);
            }
        });
        jPanel1.add(Maximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, 50));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("\t\t   ---INFORMACION---\n  La cadena de ADN pusee multiples tripletas que la conforman, la tripleta puede estar \nformada por: adenina (A), guanina (G), citosina (C) y timina (T), al ser una gran candena\n         esta puede contener multiples veces la misma tripleta en distintas posiciones.\n   Aqui el usuario podra ver cual de Tripleta es la que mas se repite y la que menos se\n                                                                          repite.\n\t\t          \n\t\t           ---PASOS---\n                        El usuario selecionara cual desea buscar (Minimo o Maximo)\n                             y el programa le mostrara el resultado de la busqueda.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 500, 190));

        Regresar.setBackground(new java.awt.Color(255, 255, 255));
        Regresar.setForeground(new java.awt.Color(0, 0, 0));
        Regresar.setText("Regresar");
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        jPanel1.add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 458, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void ResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResultadoActionPerformed
    /**
     * Metodo que se activa al precionar al boton Minimo
     * Se encarga de darle al String Frecuencia el valor de "minimo" para que cuando el usuario precione buscar se busque el triplete con menor frecuencia 
     * @param evt 
     */
    private void MinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinimoActionPerformed
        // TODO add your handling code here:
         Resultado.setText("El triplete menos frecuentado es "+arbol.patronMenosFrecuente().getTriplete()+" con "+arbol.patronMenosFrecuente().getFrecuencia()+" veces.");
    }//GEN-LAST:event_MinimoActionPerformed
    /**
     * Metodo que se activa al precionar al boton Maximo
     * Se encarga de darle al String Frecuencia el valor de "maximo" para que cuando el usuario precione buscar se busque el triplete con mayor frecuencia 
     * @param evt 
     */
    private void MaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaximoActionPerformed
        // TODO add your handling code here:
        Resultado.setText("El triplete mas frecuentado es "+arbol.patronMasFrecuente().getTriplete()+" con "+arbol.patronMasFrecuente().getFrecuencia()+" veces.");
    }//GEN-LAST:event_MaximoActionPerformed

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        menu.back();
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ver_Max_Min.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ver_Max_Min.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ver_Max_Min.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ver_Max_Min.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ver_Max_Min(menu).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton Maximo;
    private javax.swing.JButton Minimo;
    private javax.swing.JButton Regresar;
    private javax.swing.JTextField Resultado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
